apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.namespace }}
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: {{ .Values.prometheus.url }}
        access: proxy
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ .Values.namespace }}
data:
  sample-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "uid": null,
        "title": "Prometheus Overview",
        "tags": ["prometheus", "overview"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "type": "graph",
            "title": "Prometheus Up",
            "targets": [
              {
                "expr": "up{job=\"prometheus\"}",
                "legendFormat": "Prometheus",
                "interval": "15s"
              }
            ]
          }
        ]
      },
      "overwrite": true
    }
