namespace: app-dev

image:
  repository: mladenovskistefan/app-springboot
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

configmap:
  databaseUrl: "jdbc:postgresql://postgres-service:5432/book_shop"

database:
  username: postgres
  password: password
