namespace: app-dev

image:
  repository: mladenovskistefan/app-springboot
  tag: "v1.0.1"

service:
  type: ClusterIP
  port: 8080

configmap:
  databaseUrl: "jdbc:postgresql://postgres-service:5432/book_shop"

database:
  username: placeholder-username
  password: placeholder-password
