apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  namespace: {{ .Values.namespace }}
data:
  postgres_exporter.yml: |
    datasource:
      user: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
      host: {{ .Values.postgres.host }}
      port: {{ .Values.postgres.port }}
      dbname: {{ .Values.postgres.dbname }}
    config:
      collectors:
        stat_bgwriter: {{ .Values.config.stat_bgwriter }}
        stat_activity: {{ .Values.config.stat_activity }}
        stat_database: {{ .Values.config.stat_database }}
