apiVersion: v1
kind: Secret
metadata:
  name: springboot-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
