apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: {{ .Values.namespace }}
  labels:
    app: springboot
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: springboot
